site_name: Datoviz Documentation
repo_url: https://github.com/datoviz/datoviz
site_description: High-performance interactive scientific data visualization library
site_author: Cyrille Rossant
theme:
  name: material
  logo: images/logow.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - admonition
  - attr_list
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        # on_config: "utils.hooks:config_hook"
        # on_nav: "utils.hooks:nav_hook"
        on_page_markdown: "utils.hooks:page_hook"
nav:
  - Home: 'index.md'
  - Getting started:
    - Index: 'tutorials/index.md'
    - Installation: 'tutorials/install.md'
    - Quickstart: 'tutorials/quickstart.md'
  - Examples:
    - Overview: 'examples/index.md'
    - Quickstart tutorial: 'examples/quickstart.md'
    - Image blending: 'examples/image.md'
    - France departements: 'examples/france.md'
    - Digital signals: 'examples/signals.md'
    - 3D brain mesh: 'examples/brain.md'
    - Two panels: 'examples/twopanels.md'
    - Custom colormap: 'examples/colormap.md'
    - Async event loop: 'examples/eventloop.md'
  - How to guides:
    - Index: 'howto/index.md'
    - Standalone C apps:
      - How to use the scene C API: 'howto/standalone_scene.md'
      - How to use the canvas C API: 'howto/standalone_canvas.md'
      - How to use the vklite C API: 'howto/standalone_vklite.md'
      - How to use Dear ImGui directly: 'howto/standalone_imgui.md'
    - Custom visuals and graphics:
      - How to write a custom visual: 'howto/visual.md'
      - How to write a custom graphics: 'howto/graphics.md'
  - Reference:
    - Index: 'reference/index.md'
    - Library of visuals: 'reference/visuals.md'
    - Library of graphics: 'reference/graphics.md'
    - Library of colormaps: 'reference/colormaps.md'
    - Library of controllers: 'reference/controllers.md'
  - C API reference:
    - Index: 'api/index.md'
    - Scene API: 'api/scene.md'
    - Visual API: 'api/visual.md'
    - Controller API: 'api/controller.md'
    - GUI API: 'api/gui.md'
    - Canvas API: 'api/canvas.md'
    - GPU API: 'api/gpu.md'
    - vklite API: 'api/vklite.md'
    - Misc API: 'api/misc.md'
    - Enumerations: 'api/enums.md'
  - Discussions:
    - Index: 'discussions/index.md'
    - For users:
      - Vulkan crash course: 'discussions/vulkan.md'
      - Roadmap: 'discussions/roadmap.md'
      - Best practices: 'discussions/practices.md'
      - FAQ: 'discussions/faq.md'
    - For developers:
      - Library architecture: 'discussions/architecture.md'
      - Developer notes: 'discussions/developer.md'
      - Developer checklists: 'discussions/checklists.md'
